# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_app', '0003_auto_20170226_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carousel_app.Carousel'),
        ),
    ]
