# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_app', '0006_auto_20170226_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='carousel_position_index',
        ),
    ]
